CREATE TABLE USERS (
    id SERIAL PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    firstName TEXT,
    lastName TEXT
);

CREATE TABLE WORKOUT (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    date TIMESTAMP DEFAULT NOW(),
    user_id INT REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE WORKOUT_ACTIVITY (
    id SERIAL PRIMARY KEY,
    type TEXT NOT NULL,
    distance INT NOT NULL,
    duration INT NOT NULL,
    workout_id UUID REFERENCES WORKOUT(id) ON DELETE CASCADE
);

DROP TABLE WORKOUT_ACTIVITY;
DROP TABLE WORKOUT;
DROP TABLE USERS;